## Task 01: Installation

In [57]:
# Task 01 - Installation (manual task)
# I installed Anaconda, PyTorch, TensorFlow, VS Code, and PyCharm.
print("Installation completed (manual verification).")


Installation completed (manual verification).


## Task 02: Linux Commands

In [58]:
# Task 02 - Linux Commands (theoretical)
# commands = ["pwd","ls","cd","mkdir","rm"]
# for cmd in commands:
#     print("Command:", cmd)


## Task 03 Print Statement

In [59]:
# Task 03 Print Statement
print('Hello World')

Hello World


## Task 04 Variables

In [1]:
# Task 04 Variables
x=10
name='Muhammd Junaid'
print(x,name)

10 Muhammd Junaid


## Task 05 Data Types

In [61]:
# Task 05 Data Types
a=5;b=2.5;c='hi'
print(type(a),type(b),type(c))

<class 'int'> <class 'float'> <class 'str'>


## Task 06 Input Output

In [62]:
# Task 06 Input Output
age=20
print('Age:',age)

Age: 20


## Task 07 Arithmetic

In [63]:
# Task 07 Arithmetic
a=10;b=5
print(a+b,a-b,a*b,a/b)

15 5 50 2.0


## Task 08 Comparison

In [64]:
# Task 08 Comparison
a=10;b=5
print(a>b,a==b,a!=b)

True False True


## Task 09 Logical

In [65]:
# Task 09 Logical
a=True;b=False
print(a and b,a or b)

False True


## Task 10 If

In [66]:
# Task 10 If
age=20
if age>18: print('Adult')

Adult


## Task 11 If Else

In [67]:
# Task 11 If Else
age=15
print('Adult' if age>18 else 'Minor')

Minor


## Task 12 If Elif

In [68]:
# Task 12 If Elif
marks=70

if marks>=80: print('A')
elif marks>=60: print('B')
else: print('C')

B


## Task 13 Nested If

In [69]:
# Task 13 Nested If
age=20
citizen=True
if age>18:
    if citizen:
        print('Eligible')

Eligible


## Task 14 Loop Intro

In [70]:
# Task 14 Loop Intro
for i in range(3): print(i)

0
1
2


## Task 15: For Loop

In [71]:
# Task 15
for i in range(1,6):
    print(i)


1
2
3
4
5


## Task 16: While Loop

In [72]:
# Task 16
i=1
while i<=5:
    print(i)
    i+=1


1
2
3
4
5


## Task 17: Break

In [73]:
# Task 17
for i in range(10):
    if i==5:
        break
    print(i)


0
1
2
3
4


## Task 18: Continue

In [74]:
# Task 18
for i in range(5):
    if i==2:
        continue
    print(i)


0
1
3
4


## Task 19: Loop Techniques

In [75]:
# Task 19
names=["Ali","Sara"]
for i,n in enumerate(names):
    print(i,n)


0 Ali
1 Sara


## Task 20: Function

In [76]:
# Task 20
def add(a,b):
    return a+b

print(add(2,3))


5


## Task 21–25: Data Structures

In [77]:
# Task 21 List
lst=[1,2,3]
lst.append(4)
print(lst)

# Task 22 Tuple
t=(1,2,3)
print(t[0])

# Task 23 String
s="Python"
print(s.upper())

# Task 24 Set
st={1,2,2,3}
print(st)

# Task 25 Dictionary
d={"name":"Junaid"}
print(d["name"])


[1, 2, 3, 4]
1
PYTHON
{1, 2, 3}
Junaid


## Task 26–27: Exception

In [78]:
# Task 26
try:
    int("a")
except:
    print("Error handled")

# Task 27
class MyError(Exception): pass

try:
    raise MyError("Custom")
except MyError as e:
    print(e)


Error handled
Custom


## Task 28–40: NumPy

In [79]:
# Task 28 - create numpy array
import numpy as np
arr = np.array([1, 2, 3])
print(arr)

# Task 29 - indexing
print(arr[0])

# Task 30 - slicing
print(arr[:2])

# Task 31 - data type
print(arr.dtype)

# Task 32 - copy array
copy_arr = arr.copy()
print(copy_arr)

# Task 33 - shape
print(arr.shape)

# Task 34 - reshape
arr2 = np.array([1, 2, 3, 4])
print(arr2.reshape(2, 2))

# Task 35 - iteration
for i in arr:
    print(i)

# Task 36 - joining arrays
print(np.concatenate((arr, arr)))

# Task 37 - splitting arrays
print(np.array_split(arr2, 2))

# Task 38 - searching
print(np.where(arr2 == 3))

# Task 39 - sorting
print(np.sort(arr2))

# Task 40 - random numbers
print(np.random.randint(1, 10, 3))

[1 2 3]
1
[1 2]
int64
[1 2 3]
(3,)
[[1 2]
 [3 4]]
1
2
3
[1 2 3 1 2 3]
[array([1, 2]), array([3, 4])]
(array([2]),)
[1 2 3 4]
[9 7 1]


## Task 41–48: Pandas

In [ ]:
# Task 41 - pandas basics (import)
import pandas as pd

# Task 42 - pandas installation (already done if import works)

# Task 43 - pandas series
print("pandas series")
s = pd.Series([1, 2, 3])
print(s)

# Task 44 - pandas dataframe
print("pandas dataframe")
df = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
print(df)

# Task 45 - read csv (example)
print("read csv")

df = pd.read_csv("data.csv")

# Task 46 - data analysis
print("data analysis")
print(df.describe())

# Task 47 - data cleaning
print("data cleaning")
df.dropna(inplace=True)

# Task 48 - correlation

# select only numeric columns
print("select only numeric columns")
numeric_df = df.select_dtypes(include=['number'])

print("correlation")
print(numeric_df.corr())

pandas series
0    1
1    2
2    3
dtype: int64
pandas dataframe
   A  B
0  1  3
1  2  4
read csv
data analysis
                 id       host_id      latitude     longitude         price  \
count  4.889500e+04  4.889500e+04  48895.000000  48895.000000  48895.000000   
mean   1.901714e+07  6.762001e+07     40.728949    -73.952170    152.720687   
std    1.098311e+07  7.861097e+07      0.054530      0.046157    240.154170   
min    2.539000e+03  2.438000e+03     40.499790    -74.244420      0.000000   
25%    9.471945e+06  7.822033e+06     40.690100    -73.983070     69.000000   
50%    1.967728e+07  3.079382e+07     40.723070    -73.955680    106.000000   
75%    2.915218e+07  1.074344e+08     40.763115    -73.936275    175.000000   
max    3.648724e+07  2.743213e+08     40.913060    -73.712990  10000.000000   

       minimum_nights  number_of_reviews  reviews_per_month  \
count    48895.000000       48895.000000       38843.000000   
mean         7.029962          23.274466          

## Task 49–50: Statistics

In [81]:
# Task 49 - mean median mode
import statistics

nums = [1, 2, 3, 4, 4]

print(statistics.mean(nums))
print(statistics.median(nums))
print(statistics.mode(nums))

# Task 50 - standard deviation
print(statistics.stdev(nums))

2.8
3
4
1.3038404810405297
