## Task 01: Installation

In [13]:
# Task 01 - Installation (manual task)
# I installed Anaconda, PyTorch, TensorFlow, VS Code, and PyCharm.
print("Installation completed (manual verification).")


Installation completed (manual verification).


## Task 02: Linux Commands

In [14]:
# Task 02 - Linux Commands (theoretical)
# commands = ["pwd","ls","cd","mkdir","rm"]
# for cmd in commands:
#     print("Command:", cmd)


## Task 03 Add two numbers

In [15]:
# Add two numbers

a = 5
b = 10

sum = a + b
print("Sum:", sum)

Sum: 15


## Task 4: Input + Add + Display

In [16]:
# Store input numbers
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

# Add two numbers
sum = num1 + num2

# Display the sum
print("The sum is:", sum)

The sum is: 6.0


## Task 5: Square Root (Simple)

In [17]:
# Python program to calculate the square root

# Take input from user
num = float(input("Enter a number: "))

# Calculate square root
sqrt = num ** 0.5

print("Square root is:", sqrt)

Square root is: 1.7320508075688772


## Task 6: Square Root (Real + Complex)

In [18]:
# Find square root of real and complex numbers

import cmath

# Take input from user
num = eval(input("Enter a number: "))

# Calculate square root
sqrt = cmath.sqrt(num)

print("Square root is:", sqrt)

Square root is: (1.7320508075688772+0j)


## Task 7: Celsius to Fahrenheit

In [19]:
# Python program to convert temperature

celsius = 37.5

# Formula
fahrenheit = (celsius * 9/5) + 32

print("Fahrenheit:", fahrenheit)

Fahrenheit: 99.5


## Task 8: Area of Triangle (Heron’s Formula)

In [20]:
# Python program to find the area of triangle
# a = 5
# b = 6
# c = 7
# Take input from user
a = float(input("Enter first side: "))
b = float(input("Enter second side: "))
c = float(input("Enter third side: "))

# Calculate semi-perimeter
s = (a + b + c) / 2

# Calculate area
area = (s * (s - a) * (s - b) * (s - c)) ** 0.5

print("The area of the triangle is:", area)

The area of the triangle is: 3.897114317029974


## Task 9: Quadratic Equation Solver

In [21]:
# Solve quadratic equation ax^2 + bx + c = 0

import cmath

a = 1
b = 5
c = 6

# Calculate discriminant
d = (b**2) - (4*a*c)

# Find two solutions
sol1 = (-b - cmath.sqrt(d)) / (2*a)
sol2 = (-b + cmath.sqrt(d)) / (2*a)

print("The solutions are:", sol1, "and", sol2)

The solutions are: (-3+0j) and (-2+0j)


## Task 10: Kilometers to Miles

In [22]:
# Taking kilometers input from the user
kilometers = float(input("Enter value in kilometers: "))

# Conversion factor
conv_fac = 0.621371

# Calculate miles
miles = kilometers * conv_fac

print("Miles:", miles)

Miles: 1.8641130000000001


## Task 11: Simple If Condition

In [23]:
# Simple if condition

i = 10

if i < 15:
    print("10 is less than 15")
    print("I am not in if")

10 is less than 15
I am not in if


## Task 12: If-Else Condition

In [24]:
# If-else condition

i = 20

if i < 15:
    print("i is smaller than 15")
    print("i'm in if block")
else:
    print("i is greater than 15")
    print("i'm in else block")

print("i'm not in if and not in else block")

i is greater than 15
i'm in else block
i'm not in if and not in else block


## Task 13: Nested If

In [ ]:
# Nested if statement

i = 10

if i == 10:
    # First if
    if i < 15:
        print("i is smaller than 15")

    # Nested if
    if i < 12:
        print("i is smaller than 12 too")
    else:
        print("i is greater than 15")

i is smaller than 15
i is smaller than 12 too


## Task 14: If-Elif-Else

In [26]:
# If-elif-else ladder

i = 20

if i == 10:
    print("i is 10")
elif i == 15:
    print("i is 15")
elif i == 20:
    print("i is 20")
else:
    print("i is not present")

i is 20


## Task 15: For Loop

In [27]:
# Task 15
for i in range(1,6):
    print(i)


1
2
3
4
5


## Task 16: While Loop

In [28]:
# Task 16
i=1
while i<=5:
    print(i)
    i+=1


1
2
3
4
5


## Task 17: Break

In [29]:
# Task 17
for i in range(10):
    if i==5:
        break
    print(i)


0
1
2
3
4


## Task 18: Continue

In [30]:
# Task 18
for i in range(5):
    if i==2:
        continue
    print(i)


0
1
3
4


## Task 19: Loop Techniques

In [31]:
# Task 19
names=["Ali","Sara"]
for i,n in enumerate(names):
    print(i,n)


0 Ali
1 Sara


## Task 20: Function

In [32]:
# Task 20
def add(a,b):
    return a+b

print(add(2,3))


5


## Task 21–25: Data Structures

In [33]:
# Task 21 List
lst=[1,2,3]
lst.append(4)
print(lst)

# Task 22 Tuple
t=(1,2,3)
print(t[0])

# Task 23 String
s="Python"
print(s.upper())

# Task 24 Set
st={1,2,2,3}
print(st)

# Task 25 Dictionary
d={"name":"Junaid"}
print(d["name"])


[1, 2, 3, 4]
1
PYTHON
{1, 2, 3}
Junaid


## Task 26–27: Exception

In [34]:
# Task 26
try:
    int("a")
except:
    print("Error handled")

# Task 27
class MyError(Exception): pass

try:
    raise MyError("Custom")
except MyError as e:
    print(e)


Error handled
Custom


## Task 28–40: NumPy

In [35]:
# Task 28 - create numpy array
import numpy as np
arr = np.array([1, 2, 3])
print(arr)

# Task 29 - indexing
print(arr[0])

# Task 30 - slicing
print(arr[:2])

# Task 31 - data type
print(arr.dtype)

# Task 32 - copy array
copy_arr = arr.copy()
print(copy_arr)

# Task 33 - shape
print(arr.shape)

# Task 34 - reshape
arr2 = np.array([1, 2, 3, 4])
print(arr2.reshape(2, 2))

# Task 35 - iteration
for i in arr:
    print(i)

# Task 36 - joining arrays
print(np.concatenate((arr, arr)))

# Task 37 - splitting arrays
print(np.array_split(arr2, 2))

# Task 38 - searching
print(np.where(arr2 == 3))

# Task 39 - sorting
print(np.sort(arr2))

# Task 40 - random numbers
print(np.random.randint(1, 10, 3))

[1 2 3]
1
[1 2]
int64
[1 2 3]
(3,)
[[1 2]
 [3 4]]
1
2
3
[1 2 3 1 2 3]
[array([1, 2]), array([3, 4])]
(array([2]),)
[1 2 3 4]
[9 6 7]


## Task 41–48: Pandas

In [36]:
# Task 41 - pandas basics (import)
import pandas as pd

# Task 42 - pandas installation (already done if import works)

# Task 43 - pandas series
print("pandas series")
s = pd.Series([1, 2, 3])
print(s)

# Task 44 - pandas dataframe
print("pandas dataframe")
df = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
print(df)

# Task 45 - read csv (example)
print("read csv")

df = pd.read_csv("data.csv")

# Task 46 - data analysis
print("data analysis")
print(df.describe())

# Task 47 - data cleaning
print("data cleaning")
df.dropna(inplace=True)

# Task 48 - correlation

# select only numeric columns
print("select only numeric columns")
numeric_df = df.select_dtypes(include=['number'])

print("correlation")
print(numeric_df.corr())

pandas series
0    1
1    2
2    3
dtype: int64
pandas dataframe
   A  B
0  1  3
1  2  4
read csv
data analysis
                 id       host_id      latitude     longitude         price  \
count  4.889500e+04  4.889500e+04  48895.000000  48895.000000  48895.000000   
mean   1.901714e+07  6.762001e+07     40.728949    -73.952170    152.720687   
std    1.098311e+07  7.861097e+07      0.054530      0.046157    240.154170   
min    2.539000e+03  2.438000e+03     40.499790    -74.244420      0.000000   
25%    9.471945e+06  7.822033e+06     40.690100    -73.983070     69.000000   
50%    1.967728e+07  3.079382e+07     40.723070    -73.955680    106.000000   
75%    2.915218e+07  1.074344e+08     40.763115    -73.936275    175.000000   
max    3.648724e+07  2.743213e+08     40.913060    -73.712990  10000.000000   

       minimum_nights  number_of_reviews  reviews_per_month  \
count    48895.000000       48895.000000       38843.000000   
mean         7.029962          23.274466          

## Task 49–50: Statistics

In [37]:
# Task 49 - mean median mode
import statistics

nums = [1, 2, 3, 4, 4]

print(statistics.mean(nums))
print(statistics.median(nums))
print(statistics.mode(nums))

# Task 50 - standard deviation
print(statistics.stdev(nums))

2.8
3
4
1.3038404810405297
